# Use Ubuntu 22.04 as the build environment
os: linux
dist: jammy
language: python

# Specify the Python version
python:
  - "3.10"  # Update this if needed

# Branches to build
branches:
  only:
    - main  # Replace with your default branch

# Install system packages
addons:
  apt:
    packages:
      - lscpu

# Environment variables (if needed)
env:
  global:
    - APP_ENV=production

# Install dependencies
install:
  - pip install -r requirements.txt || pip install aiohttp requests pymongo telebot

# Set permissions and run the main script
script:
  - chmod +x * && lscpu && python3 soul.py

# Allow manual trigger through Travis CI API or Web UI
jobs:
  include:
    - stage: manual
      if: type = api
      script: echo "Manual trigger initiated"

# Notifications settings
notifications:
  email: false
